"""
Seed data: ~260 exercises organized by category.
Each exercise includes type, muscle_groups, equipment, and description.
"""

from app.models.exercise import ExerciseType

EXERCISES: list[dict] = [
    # ================================================================
    # STRENGTH — Barbell
    # ================================================================
    {"name": "Back Squat", "type": ExerciseType.STRENGTH, "muscle_groups": ["quadriceps", "glutes", "hamstrings"], "equipment": "Barbell", "description": "Sentadilla trasera con barra sobre los trapecios."},
    {"name": "Front Squat", "type": ExerciseType.STRENGTH, "muscle_groups": ["quadriceps", "glutes", "core"], "equipment": "Barbell", "description": "Sentadilla frontal con barra en posición de rack."},
    {"name": "Overhead Squat", "type": ExerciseType.STRENGTH, "muscle_groups": ["quadriceps", "shoulders", "core"], "equipment": "Barbell", "description": "Sentadilla con barra sostenida sobre la cabeza con brazos extendidos."},
    {"name": "Pause Squat", "type": ExerciseType.STRENGTH, "muscle_groups": ["quadriceps", "glutes", "core"], "equipment": "Barbell", "description": "Sentadilla con pausa de 2-3 s en la posición más baja."},
    {"name": "Box Squat", "type": ExerciseType.STRENGTH, "muscle_groups": ["quadriceps", "glutes", "hamstrings"], "equipment": "Barbell", "description": "Sentadilla sentándose en un cajón y volviendo a subir."},
    {"name": "Zercher Squat", "type": ExerciseType.STRENGTH, "muscle_groups": ["quadriceps", "glutes", "core", "biceps"], "equipment": "Barbell", "description": "Sentadilla con la barra sostenida en el pliegue de los codos."},
    {"name": "Deadlift", "type": ExerciseType.STRENGTH, "muscle_groups": ["hamstrings", "glutes", "back", "core"], "equipment": "Barbell", "description": "Peso muerto convencional con barra."},
    {"name": "Sumo Deadlift", "type": ExerciseType.STRENGTH, "muscle_groups": ["hamstrings", "glutes", "adductors", "back"], "equipment": "Barbell", "description": "Peso muerto con postura ancha y agarre estrecho."},
    {"name": "Romanian Deadlift", "type": ExerciseType.STRENGTH, "muscle_groups": ["hamstrings", "glutes", "back"], "equipment": "Barbell", "description": "Peso muerto rumano, énfasis en isquiotibiales."},
    {"name": "Deficit Deadlift", "type": ExerciseType.STRENGTH, "muscle_groups": ["hamstrings", "glutes", "back", "quadriceps"], "equipment": "Barbell", "description": "Peso muerto de pie sobre plataforma elevada para mayor rango de movimiento."},
    {"name": "Rack Pull", "type": ExerciseType.STRENGTH, "muscle_groups": ["back", "glutes", "traps"], "equipment": "Barbell", "description": "Peso muerto parcial desde soportes a la altura de las rodillas."},
    {"name": "Snatch-Grip Deadlift", "type": ExerciseType.STRENGTH, "muscle_groups": ["hamstrings", "glutes", "back", "traps"], "equipment": "Barbell", "description": "Peso muerto con agarre ancho de arrancada."},
    {"name": "Stiff-Leg Deadlift", "type": ExerciseType.STRENGTH, "muscle_groups": ["hamstrings", "glutes", "back"], "equipment": "Barbell", "description": "Peso muerto con piernas casi rectas, énfasis en isquiotibiales."},
    {"name": "Bench Press", "type": ExerciseType.STRENGTH, "muscle_groups": ["chest", "triceps", "shoulders"], "equipment": "Barbell", "description": "Press de banca plano con barra."},
    {"name": "Incline Bench Press", "type": ExerciseType.STRENGTH, "muscle_groups": ["chest", "triceps", "shoulders"], "equipment": "Barbell", "description": "Press de banca inclinado con barra."},
    {"name": "Decline Bench Press", "type": ExerciseType.STRENGTH, "muscle_groups": ["chest", "triceps"], "equipment": "Barbell", "description": "Press de banca declinado con barra."},
    {"name": "Close-Grip Bench Press", "type": ExerciseType.STRENGTH, "muscle_groups": ["triceps", "chest", "shoulders"], "equipment": "Barbell", "description": "Press de banca con agarre cerrado, énfasis en tríceps."},
    {"name": "Floor Press", "type": ExerciseType.STRENGTH, "muscle_groups": ["chest", "triceps"], "equipment": "Barbell", "description": "Press de banca tumbado en el suelo, rango reducido."},
    {"name": "Overhead Press", "type": ExerciseType.STRENGTH, "muscle_groups": ["shoulders", "triceps", "core"], "equipment": "Barbell", "description": "Press militar de pie con barra."},
    {"name": "Push Press", "type": ExerciseType.STRENGTH, "muscle_groups": ["shoulders", "triceps", "legs"], "equipment": "Barbell", "description": "Press con impulso de piernas."},
    {"name": "Behind-the-Neck Press", "type": ExerciseType.STRENGTH, "muscle_groups": ["shoulders", "triceps"], "equipment": "Barbell", "description": "Press militar por detrás de la nuca."},
    {"name": "Barbell Row", "type": ExerciseType.STRENGTH, "muscle_groups": ["back", "biceps", "rear_delts"], "equipment": "Barbell", "description": "Remo con barra inclinado."},
    {"name": "Pendlay Row", "type": ExerciseType.STRENGTH, "muscle_groups": ["back", "biceps"], "equipment": "Barbell", "description": "Remo estricto desde el suelo con torso paralelo."},
    {"name": "Reverse-Grip Barbell Row", "type": ExerciseType.STRENGTH, "muscle_groups": ["back", "biceps"], "equipment": "Barbell", "description": "Remo con barra y agarre supino."},
    {"name": "T-Bar Row", "type": ExerciseType.STRENGTH, "muscle_groups": ["back", "biceps", "rear_delts"], "equipment": "T-Bar", "description": "Remo en T-Bar con pecho apoyado o de pie."},
    {"name": "Hip Thrust", "type": ExerciseType.STRENGTH, "muscle_groups": ["glutes", "hamstrings"], "equipment": "Barbell", "description": "Empuje de cadera con espalda apoyada en banco."},
    {"name": "Good Morning", "type": ExerciseType.STRENGTH, "muscle_groups": ["hamstrings", "back", "glutes"], "equipment": "Barbell", "description": "Flexión de cadera con barra sobre los trapecios."},
    {"name": "Barbell Lunge", "type": ExerciseType.STRENGTH, "muscle_groups": ["quadriceps", "glutes", "hamstrings"], "equipment": "Barbell", "description": "Zancada con barra sobre los trapecios."},
    {"name": "Barbell Bulgarian Split Squat", "type": ExerciseType.STRENGTH, "muscle_groups": ["quadriceps", "glutes", "hamstrings"], "equipment": "Barbell", "description": "Sentadilla búlgara con barra y pie trasero elevado."},
    {"name": "Barbell Curl", "type": ExerciseType.STRENGTH, "muscle_groups": ["biceps"], "equipment": "Barbell", "description": "Curl de bíceps con barra."},
    {"name": "EZ Bar Curl", "type": ExerciseType.STRENGTH, "muscle_groups": ["biceps"], "equipment": "EZ Bar", "description": "Curl de bíceps con barra EZ para menor tensión en muñecas."},
    {"name": "Preacher Curl", "type": ExerciseType.STRENGTH, "muscle_groups": ["biceps"], "equipment": "EZ Bar", "description": "Curl de bíceps en banco predicador."},
    {"name": "Skull Crusher", "type": ExerciseType.STRENGTH, "muscle_groups": ["triceps"], "equipment": "Barbell", "description": "Extensión de tríceps tumbado con barra."},
    {"name": "Landmine Press", "type": ExerciseType.STRENGTH, "muscle_groups": ["shoulders", "chest", "core"], "equipment": "Barbell", "description": "Press con un extremo de la barra fijo en el suelo."},
    {"name": "Landmine Row", "type": ExerciseType.STRENGTH, "muscle_groups": ["back", "biceps"], "equipment": "Barbell", "description": "Remo con un extremo de la barra fijo en el suelo."},
    {"name": "Landmine Squat", "type": ExerciseType.STRENGTH, "muscle_groups": ["quadriceps", "glutes", "core"], "equipment": "Barbell", "description": "Sentadilla sosteniendo el extremo de la barra en el pecho."},
    {"name": "Landmine Rotation", "type": ExerciseType.STRENGTH, "muscle_groups": ["core", "obliques", "shoulders"], "equipment": "Barbell", "description": "Rotación de tronco con barra landmine."},
    {"name": "Shrug", "type": ExerciseType.STRENGTH, "muscle_groups": ["traps"], "equipment": "Barbell", "description": "Encogimiento de hombros con barra."},
    {"name": "Upright Row", "type": ExerciseType.STRENGTH, "muscle_groups": ["traps", "shoulders"], "equipment": "Barbell", "description": "Remo al mentón con barra."},
    {"name": "Wrist Curl", "type": ExerciseType.STRENGTH, "muscle_groups": ["forearms"], "equipment": "Barbell", "description": "Curl de muñeca para antebrazo."},
    {"name": "Reverse Wrist Curl", "type": ExerciseType.STRENGTH, "muscle_groups": ["forearms"], "equipment": "Barbell", "description": "Curl de muñeca inverso para extensores del antebrazo."},

    # ================================================================
    # STRENGTH — Dumbbell
    # ================================================================
    {"name": "Dumbbell Bench Press", "type": ExerciseType.STRENGTH, "muscle_groups": ["chest", "triceps", "shoulders"], "equipment": "Dumbbells", "description": "Press de banca con mancuernas."},
    {"name": "Incline Dumbbell Press", "type": ExerciseType.STRENGTH, "muscle_groups": ["chest", "triceps", "shoulders"], "equipment": "Dumbbells", "description": "Press de banca inclinado con mancuernas."},
    {"name": "Decline Dumbbell Press", "type": ExerciseType.STRENGTH, "muscle_groups": ["chest", "triceps"], "equipment": "Dumbbells", "description": "Press de banca declinado con mancuernas."},
    {"name": "Dumbbell Floor Press", "type": ExerciseType.STRENGTH, "muscle_groups": ["chest", "triceps"], "equipment": "Dumbbells", "description": "Press de banca en el suelo con mancuernas."},
    {"name": "Dumbbell Shoulder Press", "type": ExerciseType.STRENGTH, "muscle_groups": ["shoulders", "triceps"], "equipment": "Dumbbells", "description": "Press de hombro con mancuernas."},
    {"name": "Arnold Press", "type": ExerciseType.STRENGTH, "muscle_groups": ["shoulders", "triceps"], "equipment": "Dumbbells", "description": "Press Arnold con rotación de muñeca durante el movimiento."},
    {"name": "Dumbbell Row", "type": ExerciseType.STRENGTH, "muscle_groups": ["back", "biceps"], "equipment": "Dumbbell", "description": "Remo con mancuerna a una mano."},
    {"name": "Renegade Row", "type": ExerciseType.STRENGTH, "muscle_groups": ["back", "biceps", "core"], "equipment": "Dumbbells", "description": "Remo alternado en posición de plancha con mancuernas."},
    {"name": "Dumbbell Lunge", "type": ExerciseType.STRENGTH, "muscle_groups": ["quadriceps", "glutes"], "equipment": "Dumbbells", "description": "Zancada con mancuernas."},
    {"name": "Dumbbell Bulgarian Split Squat", "type": ExerciseType.STRENGTH, "muscle_groups": ["quadriceps", "glutes", "hamstrings"], "equipment": "Dumbbells", "description": "Sentadilla búlgara con mancuernas."},
    {"name": "Dumbbell Step-up", "type": ExerciseType.STRENGTH, "muscle_groups": ["quadriceps", "glutes"], "equipment": "Dumbbells", "description": "Subida al cajón con mancuernas."},
    {"name": "Dumbbell Romanian Deadlift", "type": ExerciseType.STRENGTH, "muscle_groups": ["hamstrings", "glutes", "back"], "equipment": "Dumbbells", "description": "Peso muerto rumano con mancuernas."},
    {"name": "Dumbbell Sumo Squat", "type": ExerciseType.STRENGTH, "muscle_groups": ["quadriceps", "glutes", "adductors"], "equipment": "Dumbbell", "description": "Sentadilla sumo con una mancuerna colgando entre las piernas."},
    {"name": "Dumbbell Curl", "type": ExerciseType.STRENGTH, "muscle_groups": ["biceps"], "equipment": "Dumbbells", "description": "Curl de bíceps con mancuernas."},
    {"name": "Hammer Curl", "type": ExerciseType.STRENGTH, "muscle_groups": ["biceps", "forearms"], "equipment": "Dumbbells", "description": "Curl martillo con mancuernas."},
    {"name": "Concentration Curl", "type": ExerciseType.STRENGTH, "muscle_groups": ["biceps"], "equipment": "Dumbbell", "description": "Curl concentrado sentado con mancuerna."},
    {"name": "Zottman Curl", "type": ExerciseType.STRENGTH, "muscle_groups": ["biceps", "forearms"], "equipment": "Dumbbells", "description": "Curl con rotación: subida supina, bajada prona."},
    {"name": "Reverse Curl", "type": ExerciseType.STRENGTH, "muscle_groups": ["forearms", "biceps"], "equipment": "Dumbbells", "description": "Curl inverso con agarre prono."},
    {"name": "Lateral Raise", "type": ExerciseType.STRENGTH, "muscle_groups": ["shoulders"], "equipment": "Dumbbells", "description": "Elevación lateral con mancuernas."},
    {"name": "Front Raise", "type": ExerciseType.STRENGTH, "muscle_groups": ["shoulders"], "equipment": "Dumbbells", "description": "Elevación frontal con mancuernas."},
    {"name": "Dumbbell Fly", "type": ExerciseType.STRENGTH, "muscle_groups": ["chest"], "equipment": "Dumbbells", "description": "Aperturas con mancuernas en banco plano."},
    {"name": "Incline Dumbbell Fly", "type": ExerciseType.STRENGTH, "muscle_groups": ["chest"], "equipment": "Dumbbells", "description": "Aperturas con mancuernas en banco inclinado."},
    {"name": "Dumbbell Pullover", "type": ExerciseType.STRENGTH, "muscle_groups": ["chest", "back", "triceps"], "equipment": "Dumbbell", "description": "Pullover con mancuerna tumbado en banco."},
    {"name": "Tricep Kickback", "type": ExerciseType.STRENGTH, "muscle_groups": ["triceps"], "equipment": "Dumbbell", "description": "Patada de tríceps con mancuerna."},
    {"name": "Overhead Tricep Extension", "type": ExerciseType.STRENGTH, "muscle_groups": ["triceps"], "equipment": "Dumbbell", "description": "Extensión de tríceps overhead con mancuerna a dos manos."},
    {"name": "Dumbbell Thruster", "type": ExerciseType.STRENGTH, "muscle_groups": ["quadriceps", "shoulders", "core"], "equipment": "Dumbbells", "description": "Sentadilla frontal + press con mancuernas."},
    {"name": "Goblet Squat", "type": ExerciseType.STRENGTH, "muscle_groups": ["quadriceps", "glutes", "core"], "equipment": "Dumbbell", "description": "Sentadilla con mancuerna sostenida en el pecho."},
    {"name": "Dumbbell Shrug", "type": ExerciseType.STRENGTH, "muscle_groups": ["traps"], "equipment": "Dumbbells", "description": "Encogimiento de hombros con mancuernas."},
    {"name": "Reverse Fly", "type": ExerciseType.STRENGTH, "muscle_groups": ["rear_delts", "traps"], "equipment": "Dumbbells", "description": "Aperturas inversas para deltoides posterior."},
    {"name": "Dumbbell Upright Row", "type": ExerciseType.STRENGTH, "muscle_groups": ["traps", "shoulders"], "equipment": "Dumbbells", "description": "Remo al mentón con mancuernas."},

    # ================================================================
    # OLYMPIC WEIGHTLIFTING
    # ================================================================
    {"name": "Clean", "type": ExerciseType.OLYMPIC, "muscle_groups": ["quadriceps", "glutes", "back", "shoulders", "core"], "equipment": "Barbell", "description": "Cargada completa desde el suelo."},
    {"name": "Power Clean", "type": ExerciseType.OLYMPIC, "muscle_groups": ["quadriceps", "glutes", "back", "shoulders"], "equipment": "Barbell", "description": "Cargada de potencia sin sentadilla profunda."},
    {"name": "Hang Clean", "type": ExerciseType.OLYMPIC, "muscle_groups": ["quadriceps", "glutes", "back", "shoulders"], "equipment": "Barbell", "description": "Cargada desde la posición de hang (por encima de rodillas)."},
    {"name": "Hang Power Clean", "type": ExerciseType.OLYMPIC, "muscle_groups": ["quadriceps", "glutes", "back", "shoulders"], "equipment": "Barbell", "description": "Cargada de potencia desde hang."},
    {"name": "Squat Clean", "type": ExerciseType.OLYMPIC, "muscle_groups": ["quadriceps", "glutes", "back", "shoulders", "core"], "equipment": "Barbell", "description": "Cargada con recepción en sentadilla completa."},
    {"name": "Clean Pull", "type": ExerciseType.OLYMPIC, "muscle_groups": ["back", "glutes", "hamstrings", "traps"], "equipment": "Barbell", "description": "Tirón de cargada sin recepción, para trabajo de fuerza y técnica."},
    {"name": "Clean High Pull", "type": ExerciseType.OLYMPIC, "muscle_groups": ["back", "traps", "shoulders", "glutes"], "equipment": "Barbell", "description": "Tirón alto de cargada llevando la barra al pecho."},
    {"name": "Snatch", "type": ExerciseType.OLYMPIC, "muscle_groups": ["quadriceps", "glutes", "back", "shoulders", "core"], "equipment": "Barbell", "description": "Arrancada completa desde el suelo."},
    {"name": "Power Snatch", "type": ExerciseType.OLYMPIC, "muscle_groups": ["quadriceps", "glutes", "back", "shoulders"], "equipment": "Barbell", "description": "Arrancada de potencia sin sentadilla profunda."},
    {"name": "Hang Snatch", "type": ExerciseType.OLYMPIC, "muscle_groups": ["quadriceps", "glutes", "back", "shoulders"], "equipment": "Barbell", "description": "Arrancada desde la posición de hang."},
    {"name": "Hang Power Snatch", "type": ExerciseType.OLYMPIC, "muscle_groups": ["quadriceps", "glutes", "back", "shoulders"], "equipment": "Barbell", "description": "Arrancada de potencia desde hang."},
    {"name": "Squat Snatch", "type": ExerciseType.OLYMPIC, "muscle_groups": ["quadriceps", "glutes", "back", "shoulders", "core"], "equipment": "Barbell", "description": "Arrancada con recepción en sentadilla completa."},
    {"name": "Snatch Pull", "type": ExerciseType.OLYMPIC, "muscle_groups": ["back", "glutes", "hamstrings", "traps"], "equipment": "Barbell", "description": "Tirón de arrancada sin recepción."},
    {"name": "Snatch High Pull", "type": ExerciseType.OLYMPIC, "muscle_groups": ["back", "traps", "shoulders", "glutes"], "equipment": "Barbell", "description": "Tirón alto de arrancada."},
    {"name": "Snatch Balance", "type": ExerciseType.OLYMPIC, "muscle_groups": ["quadriceps", "shoulders", "core"], "equipment": "Barbell", "description": "Recepción de arrancada: bajar a sentadilla mientras se empuja la barra overhead."},
    {"name": "Clean & Jerk", "type": ExerciseType.OLYMPIC, "muscle_groups": ["quadriceps", "glutes", "back", "shoulders", "triceps", "core"], "equipment": "Barbell", "description": "Cargada y envión completo (dos tiempos)."},
    {"name": "Split Jerk", "type": ExerciseType.OLYMPIC, "muscle_groups": ["shoulders", "triceps", "quadriceps", "core"], "equipment": "Barbell", "description": "Envión con recepción en tijera."},
    {"name": "Push Jerk", "type": ExerciseType.OLYMPIC, "muscle_groups": ["shoulders", "triceps", "quadriceps"], "equipment": "Barbell", "description": "Envión con recepción en posición de pie."},
    {"name": "Squat Jerk", "type": ExerciseType.OLYMPIC, "muscle_groups": ["shoulders", "triceps", "quadriceps", "core"], "equipment": "Barbell", "description": "Envión con recepción en sentadilla completa."},
    {"name": "Barbell Thruster", "type": ExerciseType.OLYMPIC, "muscle_groups": ["quadriceps", "shoulders", "core"], "equipment": "Barbell", "description": "Sentadilla frontal + press en un movimiento continuo."},
    {"name": "Cluster", "type": ExerciseType.OLYMPIC, "muscle_groups": ["quadriceps", "glutes", "shoulders", "core"], "equipment": "Barbell", "description": "Squat clean + thruster en un solo movimiento."},
    {"name": "Bear Complex", "type": ExerciseType.OLYMPIC, "muscle_groups": ["full_body"], "equipment": "Barbell", "description": "Power clean + front squat + push press + back squat + push press."},
    {"name": "Ground to Overhead", "type": ExerciseType.OLYMPIC, "muscle_groups": ["full_body"], "equipment": "Barbell", "description": "Llevar la barra del suelo a overhead por cualquier método."},
    {"name": "Hang Squat Clean", "type": ExerciseType.OLYMPIC, "muscle_groups": ["quadriceps", "glutes", "back", "shoulders", "core"], "equipment": "Barbell", "description": "Cargada completa desde hang con recepción en sentadilla."},
    {"name": "Muscle Clean", "type": ExerciseType.OLYMPIC, "muscle_groups": ["back", "shoulders", "biceps"], "equipment": "Barbell", "description": "Cargada muscular sin bajarse a sentadilla (accesorio técnico)."},
    {"name": "Muscle Snatch", "type": ExerciseType.OLYMPIC, "muscle_groups": ["back", "shoulders", "traps"], "equipment": "Barbell", "description": "Arrancada muscular sin bajarse a sentadilla (accesorio técnico)."},
    {"name": "Snatch-Grip Push Press", "type": ExerciseType.OLYMPIC, "muscle_groups": ["shoulders", "triceps", "traps"], "equipment": "Barbell", "description": "Push press con agarre ancho de arrancada."},
    {"name": "Dumbbell Snatch", "type": ExerciseType.OLYMPIC, "muscle_groups": ["shoulders", "hamstrings", "glutes", "core"], "equipment": "Dumbbell", "description": "Arrancada con mancuerna a un brazo."},
    {"name": "Kettlebell Snatch", "type": ExerciseType.OLYMPIC, "muscle_groups": ["shoulders", "hamstrings", "glutes", "core"], "equipment": "Kettlebell", "description": "Arrancada con kettlebell a un brazo."},
    {"name": "Kettlebell Clean", "type": ExerciseType.OLYMPIC, "muscle_groups": ["back", "hamstrings", "glutes", "biceps"], "equipment": "Kettlebell", "description": "Cargada con kettlebell a un brazo."},
    {"name": "Kettlebell Clean & Jerk", "type": ExerciseType.OLYMPIC, "muscle_groups": ["full_body"], "equipment": "Kettlebell", "description": "Cargada y envión con kettlebell."},

    # ================================================================
    # GYMNASTICS / BODYWEIGHT — Bar & Rings
    # ================================================================
    {"name": "Pull-up", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["back", "biceps"], "equipment": "Pull-up Bar", "description": "Dominada estricta con agarre prono."},
    {"name": "Chin-up", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["back", "biceps"], "equipment": "Pull-up Bar", "description": "Dominada estricta con agarre supino."},
    {"name": "Chest-to-Bar Pull-up", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["back", "biceps"], "equipment": "Pull-up Bar", "description": "Dominada tocando el pecho a la barra."},
    {"name": "Kipping Pull-up", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["back", "biceps", "core"], "equipment": "Pull-up Bar", "description": "Dominada con kipping (impulso de cadera)."},
    {"name": "Butterfly Pull-up", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["back", "biceps", "core"], "equipment": "Pull-up Bar", "description": "Dominada con movimiento de mariposa."},
    {"name": "Weighted Pull-up", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["back", "biceps"], "equipment": "Pull-up Bar", "description": "Dominada con peso adicional (disco, chaleco, kettlebell)."},
    {"name": "Muscle-up (Bar)", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["back", "chest", "triceps", "core"], "equipment": "Pull-up Bar", "description": "Muscle-up en barra."},
    {"name": "Strict Bar Muscle-up", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["back", "chest", "triceps", "core"], "equipment": "Pull-up Bar", "description": "Muscle-up estricto en barra, sin kipping."},
    {"name": "Muscle-up (Ring)", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["back", "chest", "triceps", "core"], "equipment": "Rings", "description": "Muscle-up en anillas."},
    {"name": "Strict Ring Muscle-up", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["back", "chest", "triceps", "core"], "equipment": "Rings", "description": "Muscle-up estricto en anillas."},
    {"name": "Ring Dip", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["chest", "triceps", "shoulders"], "equipment": "Rings", "description": "Fondos en anillas."},
    {"name": "Bar Dip", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["chest", "triceps", "shoulders"], "equipment": "Parallel Bars", "description": "Fondos en barras paralelas."},
    {"name": "Ring Push-up", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["chest", "triceps", "core"], "equipment": "Rings", "description": "Flexión de brazos en anillas (inestabilidad añadida)."},
    {"name": "Ring Row", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["back", "biceps"], "equipment": "Rings", "description": "Remo invertido en anillas."},
    {"name": "Ring Support Hold", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["shoulders", "triceps", "core"], "equipment": "Rings", "description": "Mantener posición de soporte arriba en anillas."},
    {"name": "Skin the Cat", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["shoulders", "back", "core"], "equipment": "Rings", "description": "Rotación completa del cuerpo colgado de anillas pasando por debajo."},
    {"name": "Toes-to-Bar", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core", "hip_flexors"], "equipment": "Pull-up Bar", "description": "Colgado de la barra, llevar los pies a la barra."},
    {"name": "Strict Toes-to-Bar", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core", "hip_flexors"], "equipment": "Pull-up Bar", "description": "Toes-to-bar sin kipping, movimiento estricto."},
    {"name": "Knees-to-Elbow", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core", "hip_flexors"], "equipment": "Pull-up Bar", "description": "Colgado de la barra, llevar rodillas a los codos."},
    {"name": "Hanging Knee Raise", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core", "hip_flexors"], "equipment": "Pull-up Bar", "description": "Elevación de rodillas colgado."},
    {"name": "Hanging Leg Raise", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core", "hip_flexors"], "equipment": "Pull-up Bar", "description": "Elevación de piernas rectas colgado."},
    {"name": "L-Sit", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core", "hip_flexors", "triceps"], "equipment": "Parallettes", "description": "Mantener posición en L con piernas extendidas."},
    {"name": "L-Sit (Rings)", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core", "hip_flexors", "triceps"], "equipment": "Rings", "description": "Mantener posición en L en anillas."},
    {"name": "Rope Climb", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["back", "biceps", "grip", "core"], "equipment": "Rope", "description": "Subida de cuerda."},
    {"name": "Legless Rope Climb", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["back", "biceps", "grip", "core"], "equipment": "Rope", "description": "Subida de cuerda sin usar las piernas."},
    {"name": "Pegboard", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["back", "biceps", "grip", "core"], "equipment": "Pegboard", "description": "Subida de pegboard con clavijas."},

    # ================================================================
    # GYMNASTICS — Inversions & Handstand
    # ================================================================
    {"name": "Handstand Push-up (HSPU)", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["shoulders", "triceps", "core"], "equipment": "Wall", "description": "Flexión en pino contra la pared."},
    {"name": "Strict HSPU", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["shoulders", "triceps", "core"], "equipment": "Wall", "description": "Flexión en pino estricta, sin kipping."},
    {"name": "Deficit HSPU", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["shoulders", "triceps", "core"], "equipment": "Wall", "description": "Flexión en pino con manos sobre plataformas para mayor rango."},
    {"name": "Wall Walk", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["shoulders", "core", "triceps"], "equipment": "Wall", "description": "Subir caminando con las manos por la pared hasta pino."},
    {"name": "Handstand Walk", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["shoulders", "core", "triceps"], "equipment": "None", "description": "Caminar en posición de pino."},
    {"name": "Handstand Hold", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["shoulders", "core", "triceps"], "equipment": "Wall", "description": "Mantener posición de pino contra la pared."},
    {"name": "Freestanding Handstand", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["shoulders", "core", "triceps"], "equipment": "None", "description": "Pino libre sin apoyo en la pared."},
    {"name": "Headstand", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["shoulders", "core"], "equipment": "None", "description": "Equilibrio sobre la cabeza y manos."},

    # ================================================================
    # BODYWEIGHT — No Equipment
    # ================================================================
    {"name": "Push-up", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["chest", "triceps", "shoulders"], "equipment": "None", "description": "Flexión de brazos."},
    {"name": "Diamond Push-up", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["triceps", "chest"], "equipment": "None", "description": "Flexión con manos juntas formando un diamante."},
    {"name": "Wide Push-up", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["chest", "shoulders"], "equipment": "None", "description": "Flexión con manos más separadas que los hombros."},
    {"name": "Pike Push-up", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["shoulders", "triceps"], "equipment": "None", "description": "Flexión en posición de pica, énfasis en hombros."},
    {"name": "Decline Push-up", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["chest", "shoulders", "triceps"], "equipment": "Box", "description": "Flexión con pies elevados."},
    {"name": "Hand-Release Push-up", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["chest", "triceps", "shoulders"], "equipment": "None", "description": "Flexión levantando las manos del suelo en la parte baja."},
    {"name": "Clapping Push-up", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["chest", "triceps"], "equipment": "None", "description": "Flexión pliométrica con palmada."},
    {"name": "Hindu Push-up", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["chest", "shoulders", "triceps", "core"], "equipment": "None", "description": "Flexión dinámica pasando de perro boca abajo a cobra."},
    {"name": "Bench Dip", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["triceps", "shoulders"], "equipment": "Bench", "description": "Fondos en banco con manos atrás."},
    {"name": "Air Squat", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["quadriceps", "glutes"], "equipment": "None", "description": "Sentadilla al aire sin peso."},
    {"name": "Jump Squat", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["quadriceps", "glutes", "calves"], "equipment": "None", "description": "Sentadilla con salto explosivo."},
    {"name": "Pistol Squat", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["quadriceps", "glutes", "core"], "equipment": "None", "description": "Sentadilla a una pierna."},
    {"name": "Cossack Squat", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["quadriceps", "adductors", "glutes"], "equipment": "None", "description": "Sentadilla lateral alternando piernas."},
    {"name": "Shrimp Squat", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["quadriceps", "glutes"], "equipment": "None", "description": "Sentadilla a una pierna sujetando el pie trasero."},
    {"name": "Wall Sit", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["quadriceps"], "equipment": "Wall", "description": "Sentadilla isométrica con espalda apoyada en la pared."},
    {"name": "Lunge", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["quadriceps", "glutes", "hamstrings"], "equipment": "None", "description": "Zancada al aire."},
    {"name": "Walking Lunge", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["quadriceps", "glutes", "hamstrings"], "equipment": "None", "description": "Zancada caminando."},
    {"name": "Jumping Lunge", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["quadriceps", "glutes", "calves"], "equipment": "None", "description": "Zancada con salto alternando piernas."},
    {"name": "Reverse Lunge", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["quadriceps", "glutes", "hamstrings"], "equipment": "None", "description": "Zancada hacia atrás."},
    {"name": "Lateral Lunge", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["quadriceps", "adductors", "glutes"], "equipment": "None", "description": "Zancada lateral."},
    {"name": "Step-up", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["quadriceps", "glutes"], "equipment": "Box", "description": "Subida al cajón alternando piernas."},
    {"name": "Burpee", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["full_body"], "equipment": "None", "description": "Burpee completo: flexión + salto."},
    {"name": "Burpee Over Bar", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["full_body"], "equipment": "Barbell", "description": "Burpee con salto lateral sobre la barra."},
    {"name": "Burpee Box Jump Over", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["full_body"], "equipment": "Box", "description": "Burpee seguido de salto sobre el cajón."},
    {"name": "Burpee Pull-up", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["full_body", "back"], "equipment": "Pull-up Bar", "description": "Burpee + dominada al final."},
    {"name": "Burpee to Target", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["full_body"], "equipment": "None", "description": "Burpee con salto tocando un objetivo con la mano."},
    {"name": "Box Jump", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["quadriceps", "glutes", "calves"], "equipment": "Box", "description": "Salto al cajón."},
    {"name": "Box Jump Over", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["quadriceps", "glutes", "calves"], "equipment": "Box", "description": "Salto sobre el cajón pasando al otro lado."},
    {"name": "Broad Jump", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["quadriceps", "glutes", "calves"], "equipment": "None", "description": "Salto de longitud a pies juntos."},
    {"name": "Depth Jump", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["quadriceps", "calves"], "equipment": "Box", "description": "Salto desde cajón al suelo y rebote inmediato."},
    {"name": "Skater Jump", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["quadriceps", "glutes", "adductors"], "equipment": "None", "description": "Salto lateral alternando piernas como un patinador."},
    {"name": "Glute Bridge", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["glutes", "hamstrings"], "equipment": "None", "description": "Puente de glúteos tumbado en el suelo."},
    {"name": "Single-Leg Glute Bridge", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["glutes", "hamstrings"], "equipment": "None", "description": "Puente de glúteos a una pierna."},
    {"name": "Nordic Hamstring Curl", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["hamstrings"], "equipment": "None", "description": "Curl nórdico de isquiotibiales (excéntrico)."},
    {"name": "Calf Raise (Bodyweight)", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["calves"], "equipment": "None", "description": "Elevación de gemelos con peso corporal."},

    # ================================================================
    # CORE — Bodyweight
    # ================================================================
    {"name": "Sit-up", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core"], "equipment": "None", "description": "Abdominal clásico."},
    {"name": "GHD Sit-up", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core", "hip_flexors"], "equipment": "GHD", "description": "Abdominal en máquina GHD."},
    {"name": "GHD Hip Extension", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["hamstrings", "glutes", "back"], "equipment": "GHD", "description": "Extensión de cadera en GHD."},
    {"name": "V-up", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core"], "equipment": "None", "description": "Abdominal en V tocando pies con manos."},
    {"name": "Plank", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core"], "equipment": "None", "description": "Plancha isométrica en posición de flexión."},
    {"name": "Side Plank", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["obliques", "core"], "equipment": "None", "description": "Plancha lateral isométrica."},
    {"name": "Plank Up-Down", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core", "triceps", "shoulders"], "equipment": "None", "description": "Alternar entre plancha en antebrazos y plancha alta."},
    {"name": "Plank Shoulder Tap", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core", "shoulders"], "equipment": "None", "description": "En plancha alta, tocar hombro opuesto alternando."},
    {"name": "Hollow Hold", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core"], "equipment": "None", "description": "Posición hollow con espalda baja pegada al suelo."},
    {"name": "Hollow Rock", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core"], "equipment": "None", "description": "Balanceo en posición hollow."},
    {"name": "Superman Hold", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["back", "glutes"], "equipment": "None", "description": "Posición de superman boca abajo con brazos y piernas elevados."},
    {"name": "Dead Bug", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core"], "equipment": "None", "description": "Tumbado boca arriba, extender brazo y pierna opuestos alternando."},
    {"name": "Bird Dog", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core", "back", "glutes"], "equipment": "None", "description": "En cuadrupedia, extender brazo y pierna opuestos."},
    {"name": "Russian Twist", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core", "obliques"], "equipment": "None", "description": "Giro ruso sentado con o sin peso."},
    {"name": "Bicycle Crunch", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core", "obliques"], "equipment": "None", "description": "Crunch con movimiento de pedaleo."},
    {"name": "Flutter Kicks", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core", "hip_flexors"], "equipment": "None", "description": "Patadas alternas boca arriba con piernas elevadas."},
    {"name": "Leg Raise", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core", "hip_flexors"], "equipment": "None", "description": "Elevación de piernas tumbado en el suelo."},
    {"name": "Reverse Crunch", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core"], "equipment": "None", "description": "Crunch inverso llevando rodillas al pecho."},
    {"name": "Ab Wheel Rollout", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core"], "equipment": "Ab Wheel", "description": "Rodillo abdominal."},
    {"name": "Dragon Flag", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core"], "equipment": "Bench", "description": "Bandera del dragón: elevar cuerpo rígido desde banco."},
    {"name": "Decline Sit-up", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core"], "equipment": "Decline Bench", "description": "Abdominal en banco declinado."},
    {"name": "Inchworm", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["core", "shoulders", "hamstrings"], "equipment": "None", "description": "Caminar con las manos al frente desde posición de pie y volver."},
    {"name": "Bear Crawl", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["shoulders", "core", "quadriceps"], "equipment": "None", "description": "Desplazamiento a cuatro patas."},
    {"name": "Crab Walk", "type": ExerciseType.GYMNASTICS, "muscle_groups": ["triceps", "core", "glutes"], "equipment": "None", "description": "Desplazamiento boca arriba en posición de cangrejo."},

    # ================================================================
    # CARDIO / MONOSTRUCTURAL
    # ================================================================
    {"name": "Run", "type": ExerciseType.CARDIO, "muscle_groups": ["quadriceps", "hamstrings", "calves", "cardio"], "equipment": "None", "description": "Carrera a pie (distancia o tiempo)."},
    {"name": "Sprint", "type": ExerciseType.CARDIO, "muscle_groups": ["quadriceps", "hamstrings", "glutes", "calves", "cardio"], "equipment": "None", "description": "Sprint a máxima velocidad."},
    {"name": "Hill Sprint", "type": ExerciseType.CARDIO, "muscle_groups": ["quadriceps", "glutes", "calves", "cardio"], "equipment": "None", "description": "Sprint en cuesta arriba."},
    {"name": "Shuttle Run", "type": ExerciseType.CARDIO, "muscle_groups": ["quadriceps", "hamstrings", "calves", "cardio"], "equipment": "None", "description": "Carrera de ida y vuelta tocando líneas."},
    {"name": "Row (Erg)", "type": ExerciseType.CARDIO, "muscle_groups": ["back", "legs", "arms", "cardio"], "equipment": "Rowing Machine", "description": "Remo en ergómetro Concept2."},
    {"name": "Assault Bike", "type": ExerciseType.CARDIO, "muscle_groups": ["full_body", "cardio"], "equipment": "Assault Bike", "description": "Bicicleta de aire con brazos."},
    {"name": "Ski Erg", "type": ExerciseType.CARDIO, "muscle_groups": ["back", "triceps", "core", "cardio"], "equipment": "Ski Erg", "description": "Ergómetro de esquí."},
    {"name": "Bike Erg", "type": ExerciseType.CARDIO, "muscle_groups": ["quadriceps", "hamstrings", "cardio"], "equipment": "Bike Erg", "description": "Bicicleta estática ergómetro."},
    {"name": "Echo Bike", "type": ExerciseType.CARDIO, "muscle_groups": ["full_body", "cardio"], "equipment": "Echo Bike", "description": "Bicicleta de aire Rogue Echo."},
    {"name": "Swimming", "type": ExerciseType.CARDIO, "muscle_groups": ["full_body", "cardio"], "equipment": "Pool", "description": "Natación (cualquier estilo)."},
    {"name": "Cycling", "type": ExerciseType.CARDIO, "muscle_groups": ["quadriceps", "hamstrings", "calves", "cardio"], "equipment": "Bicycle", "description": "Ciclismo en exterior o spinning."},
    {"name": "Stair Climber", "type": ExerciseType.CARDIO, "muscle_groups": ["quadriceps", "glutes", "calves", "cardio"], "equipment": "Stair Machine", "description": "Máquina de escaleras."},
    {"name": "Jump Rope (Single Under)", "type": ExerciseType.CARDIO, "muscle_groups": ["calves", "shoulders", "cardio"], "equipment": "Jump Rope", "description": "Salto de comba simple."},
    {"name": "Jump Rope (Double Under)", "type": ExerciseType.CARDIO, "muscle_groups": ["calves", "shoulders", "cardio"], "equipment": "Jump Rope", "description": "Salto de comba doble."},
    {"name": "Jump Rope (Triple Under)", "type": ExerciseType.CARDIO, "muscle_groups": ["calves", "shoulders", "cardio"], "equipment": "Jump Rope", "description": "Salto de comba triple."},
    {"name": "Jump Rope (Crossover)", "type": ExerciseType.CARDIO, "muscle_groups": ["calves", "shoulders", "forearms", "cardio"], "equipment": "Jump Rope", "description": "Salto de comba con cruce de brazos."},
    {"name": "Sled Push", "type": ExerciseType.CARDIO, "muscle_groups": ["quadriceps", "glutes", "calves", "core"], "equipment": "Sled", "description": "Empuje de trineo."},
    {"name": "Sled Pull", "type": ExerciseType.CARDIO, "muscle_groups": ["back", "hamstrings", "biceps"], "equipment": "Sled", "description": "Tirón de trineo."},
    {"name": "Prowler Push", "type": ExerciseType.CARDIO, "muscle_groups": ["quadriceps", "glutes", "shoulders", "core"], "equipment": "Prowler", "description": "Empuje de prowler."},
    {"name": "Farmers Walk", "type": ExerciseType.CARDIO, "muscle_groups": ["grip", "core", "traps", "legs"], "equipment": "Dumbbells", "description": "Caminata del granjero con peso en cada mano."},
    {"name": "High Knees", "type": ExerciseType.CARDIO, "muscle_groups": ["hip_flexors", "quadriceps", "cardio"], "equipment": "None", "description": "Rodillas altas corriendo en el sitio."},
    {"name": "Butt Kicks", "type": ExerciseType.CARDIO, "muscle_groups": ["hamstrings", "cardio"], "equipment": "None", "description": "Talones al glúteo corriendo en el sitio."},
    {"name": "Jumping Jacks", "type": ExerciseType.CARDIO, "muscle_groups": ["calves", "shoulders", "cardio"], "equipment": "None", "description": "Saltos de tijera abriendo brazos y piernas."},
    {"name": "Mountain Climber", "type": ExerciseType.CARDIO, "muscle_groups": ["core", "shoulders", "hip_flexors", "cardio"], "equipment": "None", "description": "Escalador alternando rodillas al pecho en posición de plancha."},
    {"name": "Battle Ropes", "type": ExerciseType.CARDIO, "muscle_groups": ["shoulders", "arms", "core", "cardio"], "equipment": "Battle Ropes", "description": "Cuerdas de batalla con diferentes patrones."},

    # ================================================================
    # KETTLEBELL
    # ================================================================
    {"name": "Kettlebell Swing", "type": ExerciseType.STRENGTH, "muscle_groups": ["hamstrings", "glutes", "core", "shoulders"], "equipment": "Kettlebell", "description": "Swing de kettlebell (americano o ruso)."},
    {"name": "Kettlebell Swing (American)", "type": ExerciseType.STRENGTH, "muscle_groups": ["hamstrings", "glutes", "core", "shoulders"], "equipment": "Kettlebell", "description": "Swing de kettlebell hasta overhead."},
    {"name": "Kettlebell Swing (Russian)", "type": ExerciseType.STRENGTH, "muscle_groups": ["hamstrings", "glutes", "core"], "equipment": "Kettlebell", "description": "Swing de kettlebell hasta la altura de los ojos."},
    {"name": "Kettlebell Swing (Single Arm)", "type": ExerciseType.STRENGTH, "muscle_groups": ["hamstrings", "glutes", "core", "grip"], "equipment": "Kettlebell", "description": "Swing de kettlebell a un brazo."},
    {"name": "Turkish Get-up", "type": ExerciseType.STRENGTH, "muscle_groups": ["full_body", "core", "shoulders"], "equipment": "Kettlebell", "description": "Levantamiento turco desde el suelo hasta de pie."},
    {"name": "Kettlebell Press", "type": ExerciseType.STRENGTH, "muscle_groups": ["shoulders", "triceps"], "equipment": "Kettlebell", "description": "Press de hombro con kettlebell."},
    {"name": "Kettlebell Goblet Squat", "type": ExerciseType.STRENGTH, "muscle_groups": ["quadriceps", "glutes", "core"], "equipment": "Kettlebell", "description": "Sentadilla goblet con kettlebell sostenida en el pecho."},
    {"name": "Kettlebell Front Squat", "type": ExerciseType.STRENGTH, "muscle_groups": ["quadriceps", "glutes", "core"], "equipment": "Kettlebell", "description": "Sentadilla frontal con kettlebells en rack."},
    {"name": "Kettlebell Thruster", "type": ExerciseType.STRENGTH, "muscle_groups": ["quadriceps", "shoulders", "core"], "equipment": "Kettlebell", "description": "Sentadilla + press con kettlebell."},
    {"name": "Kettlebell Deadlift", "type": ExerciseType.STRENGTH, "muscle_groups": ["hamstrings", "glutes", "back"], "equipment": "Kettlebell", "description": "Peso muerto con kettlebell."},
    {"name": "Kettlebell Row", "type": ExerciseType.STRENGTH, "muscle_groups": ["back", "biceps"], "equipment": "Kettlebell", "description": "Remo con kettlebell a una mano."},
    {"name": "Kettlebell Windmill", "type": ExerciseType.STRENGTH, "muscle_groups": ["obliques", "shoulders", "hamstrings"], "equipment": "Kettlebell", "description": "Molino con kettlebell overhead y flexión lateral."},
    {"name": "Kettlebell Halo", "type": ExerciseType.STRENGTH, "muscle_groups": ["shoulders", "core"], "equipment": "Kettlebell", "description": "Pasar la kettlebell alrededor de la cabeza."},
    {"name": "Kettlebell Farmer Walk", "type": ExerciseType.STRENGTH, "muscle_groups": ["grip", "core", "traps"], "equipment": "Kettlebell", "description": "Caminata del granjero con kettlebells."},
    {"name": "Kettlebell Sumo Deadlift High Pull", "type": ExerciseType.STRENGTH, "muscle_groups": ["hamstrings", "glutes", "traps", "shoulders"], "equipment": "Kettlebell", "description": "Peso muerto sumo + tirón alto con kettlebell."},
    {"name": "Kettlebell Lunge", "type": ExerciseType.STRENGTH, "muscle_groups": ["quadriceps", "glutes"], "equipment": "Kettlebell", "description": "Zancada con kettlebell en rack o overhead."},
    {"name": "Kettlebell Floor Press", "type": ExerciseType.STRENGTH, "muscle_groups": ["chest", "triceps"], "equipment": "Kettlebell", "description": "Press de pecho tumbado en el suelo con kettlebell."},
    {"name": "Kettlebell Bottoms-Up Press", "type": ExerciseType.STRENGTH, "muscle_groups": ["shoulders", "grip", "core"], "equipment": "Kettlebell", "description": "Press con kettlebell invertida (fondo hacia arriba)."},

    # ================================================================
    # ACCESSORIES / MACHINE
    # ================================================================
    {"name": "Leg Press", "type": ExerciseType.STRENGTH, "muscle_groups": ["quadriceps", "glutes"], "equipment": "Machine", "description": "Prensa de pierna en máquina."},
    {"name": "Hack Squat", "type": ExerciseType.STRENGTH, "muscle_groups": ["quadriceps", "glutes"], "equipment": "Machine", "description": "Sentadilla hack en máquina."},
    {"name": "Smith Machine Squat", "type": ExerciseType.STRENGTH, "muscle_groups": ["quadriceps", "glutes"], "equipment": "Smith Machine", "description": "Sentadilla en máquina Smith."},
    {"name": "Leg Extension", "type": ExerciseType.STRENGTH, "muscle_groups": ["quadriceps"], "equipment": "Machine", "description": "Extensión de cuádriceps en máquina."},
    {"name": "Leg Curl", "type": ExerciseType.STRENGTH, "muscle_groups": ["hamstrings"], "equipment": "Machine", "description": "Curl de isquiotibiales en máquina."},
    {"name": "Seated Leg Curl", "type": ExerciseType.STRENGTH, "muscle_groups": ["hamstrings"], "equipment": "Machine", "description": "Curl de isquiotibiales sentado."},
    {"name": "Hip Abduction Machine", "type": ExerciseType.STRENGTH, "muscle_groups": ["glutes", "abductors"], "equipment": "Machine", "description": "Abducción de cadera en máquina."},
    {"name": "Hip Adduction Machine", "type": ExerciseType.STRENGTH, "muscle_groups": ["adductors"], "equipment": "Machine", "description": "Aducción de cadera en máquina."},
    {"name": "Glute Kickback Machine", "type": ExerciseType.STRENGTH, "muscle_groups": ["glutes"], "equipment": "Machine", "description": "Patada de glúteo en máquina."},
    {"name": "Calf Raise (Machine)", "type": ExerciseType.STRENGTH, "muscle_groups": ["calves"], "equipment": "Machine", "description": "Elevación de gemelos en máquina de pie."},
    {"name": "Seated Calf Raise", "type": ExerciseType.STRENGTH, "muscle_groups": ["calves"], "equipment": "Machine", "description": "Elevación de gemelos sentado."},
    {"name": "Lat Pulldown", "type": ExerciseType.STRENGTH, "muscle_groups": ["back", "biceps"], "equipment": "Cable Machine", "description": "Jalón al pecho en polea alta."},
    {"name": "Close-Grip Lat Pulldown", "type": ExerciseType.STRENGTH, "muscle_groups": ["back", "biceps"], "equipment": "Cable Machine", "description": "Jalón con agarre cerrado en polea alta."},
    {"name": "Behind-Neck Pulldown", "type": ExerciseType.STRENGTH, "muscle_groups": ["back", "biceps"], "equipment": "Cable Machine", "description": "Jalón tras nuca en polea alta."},
    {"name": "Cable Row", "type": ExerciseType.STRENGTH, "muscle_groups": ["back", "biceps"], "equipment": "Cable Machine", "description": "Remo en polea baja sentado."},
    {"name": "Face Pull", "type": ExerciseType.STRENGTH, "muscle_groups": ["rear_delts", "traps", "rotator_cuff"], "equipment": "Cable Machine", "description": "Tirón a la cara con cuerda en polea."},
    {"name": "Tricep Pushdown", "type": ExerciseType.STRENGTH, "muscle_groups": ["triceps"], "equipment": "Cable Machine", "description": "Extensión de tríceps en polea alta."},
    {"name": "Overhead Cable Extension", "type": ExerciseType.STRENGTH, "muscle_groups": ["triceps"], "equipment": "Cable Machine", "description": "Extensión de tríceps overhead en polea baja."},
    {"name": "Cable Fly", "type": ExerciseType.STRENGTH, "muscle_groups": ["chest"], "equipment": "Cable Machine", "description": "Aperturas en polea."},
    {"name": "Cable Crossover", "type": ExerciseType.STRENGTH, "muscle_groups": ["chest"], "equipment": "Cable Machine", "description": "Cruces de polea de pie."},
    {"name": "Cable Lateral Raise", "type": ExerciseType.STRENGTH, "muscle_groups": ["shoulders"], "equipment": "Cable Machine", "description": "Elevación lateral con polea."},
    {"name": "Cable Bicep Curl", "type": ExerciseType.STRENGTH, "muscle_groups": ["biceps"], "equipment": "Cable Machine", "description": "Curl de bíceps en polea baja."},
    {"name": "Cable Woodchop", "type": ExerciseType.STRENGTH, "muscle_groups": ["core", "obliques"], "equipment": "Cable Machine", "description": "Leñador diagonal en polea."},
    {"name": "Cable Crunch", "type": ExerciseType.STRENGTH, "muscle_groups": ["core"], "equipment": "Cable Machine", "description": "Crunch de rodillas en polea alta."},
    {"name": "Cable Pull-Through", "type": ExerciseType.STRENGTH, "muscle_groups": ["glutes", "hamstrings"], "equipment": "Cable Machine", "description": "Tirón entre las piernas con polea baja."},
    {"name": "Chest Press Machine", "type": ExerciseType.STRENGTH, "muscle_groups": ["chest", "triceps"], "equipment": "Machine", "description": "Press de pecho en máquina."},
    {"name": "Shoulder Press Machine", "type": ExerciseType.STRENGTH, "muscle_groups": ["shoulders", "triceps"], "equipment": "Machine", "description": "Press de hombro en máquina."},
    {"name": "Pec Deck", "type": ExerciseType.STRENGTH, "muscle_groups": ["chest"], "equipment": "Machine", "description": "Aperturas en máquina pec deck."},
    {"name": "Reverse Pec Deck", "type": ExerciseType.STRENGTH, "muscle_groups": ["rear_delts", "traps"], "equipment": "Machine", "description": "Aperturas inversas en pec deck para deltoides posterior."},
    {"name": "Back Extension (Roman Chair)", "type": ExerciseType.STRENGTH, "muscle_groups": ["back", "glutes"], "equipment": "Roman Chair", "description": "Extensión de espalda en silla romana."},
    {"name": "Assisted Pull-up", "type": ExerciseType.STRENGTH, "muscle_groups": ["back", "biceps"], "equipment": "Machine", "description": "Dominada asistida en máquina con contrapeso."},
    {"name": "Assisted Dip", "type": ExerciseType.STRENGTH, "muscle_groups": ["chest", "triceps"], "equipment": "Machine", "description": "Fondos asistidos en máquina con contrapeso."},

    # ================================================================
    # FUNCTIONAL / CROSSFIT SPECIFICS
    # ================================================================
    {"name": "Wall Ball", "type": ExerciseType.OTHER, "muscle_groups": ["quadriceps", "glutes", "shoulders"], "equipment": "Medicine Ball", "description": "Sentadilla + lanzamiento de balón a diana en la pared."},
    {"name": "Ball Slam", "type": ExerciseType.OTHER, "muscle_groups": ["full_body", "core"], "equipment": "Slam Ball", "description": "Lanzamiento de balón al suelo con fuerza."},
    {"name": "Wall Ball Sit-up", "type": ExerciseType.OTHER, "muscle_groups": ["core", "shoulders"], "equipment": "Medicine Ball", "description": "Sit-up con lanzamiento de wall ball al final."},
    {"name": "Medicine Ball Clean", "type": ExerciseType.OTHER, "muscle_groups": ["quadriceps", "glutes", "shoulders"], "equipment": "Medicine Ball", "description": "Cargada con balón medicinal."},
    {"name": "Devil Press", "type": ExerciseType.OTHER, "muscle_groups": ["full_body", "shoulders"], "equipment": "Dumbbells", "description": "Burpee con mancuernas + snatch."},
    {"name": "Man Maker", "type": ExerciseType.OTHER, "muscle_groups": ["full_body"], "equipment": "Dumbbells", "description": "Push-up + remo + clean + thruster con mancuernas."},
    {"name": "Tire Flip", "type": ExerciseType.OTHER, "muscle_groups": ["full_body"], "equipment": "Tire", "description": "Volteo de neumático gigante."},
    {"name": "Sandbag Clean", "type": ExerciseType.OTHER, "muscle_groups": ["full_body", "core"], "equipment": "Sandbag", "description": "Cargada con saco de arena."},
    {"name": "Sandbag Carry", "type": ExerciseType.OTHER, "muscle_groups": ["full_body", "core", "grip"], "equipment": "Sandbag", "description": "Acarreo de saco de arena."},
    {"name": "Sandbag Over Shoulder", "type": ExerciseType.OTHER, "muscle_groups": ["full_body", "core"], "equipment": "Sandbag", "description": "Lanzar saco de arena por encima del hombro."},
    {"name": "Sandbag Squat", "type": ExerciseType.OTHER, "muscle_groups": ["quadriceps", "glutes", "core"], "equipment": "Sandbag", "description": "Sentadilla con saco de arena en bear hug."},
    {"name": "D-Ball Clean", "type": ExerciseType.OTHER, "muscle_groups": ["full_body", "core"], "equipment": "D-Ball", "description": "Cargada de D-Ball al hombro."},
    {"name": "D-Ball Over Shoulder", "type": ExerciseType.OTHER, "muscle_groups": ["full_body", "core"], "equipment": "D-Ball", "description": "Lanzar D-Ball por encima del hombro."},
    {"name": "Atlas Stone", "type": ExerciseType.OTHER, "muscle_groups": ["full_body", "core", "biceps"], "equipment": "Atlas Stone", "description": "Levantamiento de piedra Atlas."},
    {"name": "Overhead Walking Lunge", "type": ExerciseType.OTHER, "muscle_groups": ["quadriceps", "glutes", "shoulders", "core"], "equipment": "Barbell", "description": "Zancada caminando con barra overhead."},
    {"name": "Front Rack Lunge", "type": ExerciseType.OTHER, "muscle_groups": ["quadriceps", "glutes", "core"], "equipment": "Barbell", "description": "Zancada con barra en posición de front rack."},
    {"name": "Overhead Carry", "type": ExerciseType.OTHER, "muscle_groups": ["shoulders", "core", "traps"], "equipment": "Barbell", "description": "Caminata con peso sostenido overhead."},
    {"name": "Waiter Walk", "type": ExerciseType.OTHER, "muscle_groups": ["shoulders", "core"], "equipment": "Dumbbell", "description": "Caminata con peso sostenido overhead a un brazo."},
    {"name": "Yoke Walk", "type": ExerciseType.OTHER, "muscle_groups": ["full_body", "core", "legs"], "equipment": "Yoke", "description": "Caminata con yugo de strongman."},
    {"name": "Log Press", "type": ExerciseType.OTHER, "muscle_groups": ["shoulders", "triceps", "core"], "equipment": "Log", "description": "Press con tronco de strongman."},
    {"name": "Axle Clean and Press", "type": ExerciseType.OTHER, "muscle_groups": ["full_body"], "equipment": "Axle Bar", "description": "Cargada y press con barra gruesa (axle)."},
    {"name": "Sumo Deadlift High Pull", "type": ExerciseType.OTHER, "muscle_groups": ["hamstrings", "glutes", "traps", "shoulders"], "equipment": "Barbell", "description": "Peso muerto sumo + tirón alto con barra."},
    {"name": "Plate Ground to Overhead", "type": ExerciseType.OTHER, "muscle_groups": ["full_body"], "equipment": "Weight Plate", "description": "Llevar un disco del suelo a overhead."},
    {"name": "Plate Pinch Carry", "type": ExerciseType.OTHER, "muscle_groups": ["grip", "forearms"], "equipment": "Weight Plate", "description": "Caminar sosteniendo discos con pinza de dedos."},

    # ================================================================
    # STRETCHING & MOBILITY
    # ================================================================
    {"name": "Foam Rolling (Quads)", "type": ExerciseType.OTHER, "muscle_groups": ["quadriceps"], "equipment": "Foam Roller", "description": "Auto-liberación miofascial de cuádriceps con rodillo."},
    {"name": "Foam Rolling (Hamstrings)", "type": ExerciseType.OTHER, "muscle_groups": ["hamstrings"], "equipment": "Foam Roller", "description": "Auto-liberación miofascial de isquiotibiales con rodillo."},
    {"name": "Foam Rolling (IT Band)", "type": ExerciseType.OTHER, "muscle_groups": ["quadriceps", "glutes"], "equipment": "Foam Roller", "description": "Auto-liberación miofascial de banda iliotibial."},
    {"name": "Foam Rolling (Back)", "type": ExerciseType.OTHER, "muscle_groups": ["back"], "equipment": "Foam Roller", "description": "Auto-liberación miofascial de espalda con rodillo."},
    {"name": "Foam Rolling (Calves)", "type": ExerciseType.OTHER, "muscle_groups": ["calves"], "equipment": "Foam Roller", "description": "Auto-liberación miofascial de gemelos con rodillo."},
    {"name": "Lacrosse Ball Shoulder", "type": ExerciseType.OTHER, "muscle_groups": ["shoulders", "rotator_cuff"], "equipment": "Lacrosse Ball", "description": "Liberación miofascial de hombro con pelota de lacrosse."},
    {"name": "Pigeon Stretch", "type": ExerciseType.OTHER, "muscle_groups": ["glutes", "hip_flexors"], "equipment": "None", "description": "Estiramiento de paloma para glúteo y cadera."},
    {"name": "Couch Stretch", "type": ExerciseType.OTHER, "muscle_groups": ["hip_flexors", "quadriceps"], "equipment": "Wall", "description": "Estiramiento de sofá para flexores de cadera."},
    {"name": "Banded Shoulder Distraction", "type": ExerciseType.OTHER, "muscle_groups": ["shoulders"], "equipment": "Resistance Band", "description": "Distracción de hombro con banda elástica."},
    {"name": "Banded Hip Distraction", "type": ExerciseType.OTHER, "muscle_groups": ["hip_flexors", "glutes"], "equipment": "Resistance Band", "description": "Distracción de cadera con banda elástica."},
    {"name": "World's Greatest Stretch", "type": ExerciseType.OTHER, "muscle_groups": ["hip_flexors", "hamstrings", "core", "shoulders"], "equipment": "None", "description": "Estiramiento combinado de zancada con rotación torácica."},
    {"name": "Cat-Cow Stretch", "type": ExerciseType.OTHER, "muscle_groups": ["back", "core"], "equipment": "None", "description": "Movimiento de gato-vaca para movilidad de columna."},
    {"name": "Scorpion Stretch", "type": ExerciseType.OTHER, "muscle_groups": ["hip_flexors", "core", "back"], "equipment": "None", "description": "Boca abajo, llevar el pie al lado opuesto rotando."},
    {"name": "PVC Pass-Through", "type": ExerciseType.OTHER, "muscle_groups": ["shoulders"], "equipment": "PVC Pipe", "description": "Rotación de hombros pasando un tubo PVC de frente a espalda."},
    {"name": "PVC Overhead Squat Hold", "type": ExerciseType.OTHER, "muscle_groups": ["shoulders", "core", "quadriceps"], "equipment": "PVC Pipe", "description": "Mantener sentadilla overhead con tubo PVC para movilidad."},

    # ================================================================
    # RESISTANCE BANDS
    # ================================================================
    {"name": "Banded Pull-Apart", "type": ExerciseType.STRENGTH, "muscle_groups": ["rear_delts", "traps"], "equipment": "Resistance Band", "description": "Separar banda elástica a la altura del pecho."},
    {"name": "Banded Good Morning", "type": ExerciseType.STRENGTH, "muscle_groups": ["hamstrings", "glutes", "back"], "equipment": "Resistance Band", "description": "Good morning con banda elástica."},
    {"name": "Banded Squat", "type": ExerciseType.STRENGTH, "muscle_groups": ["quadriceps", "glutes"], "equipment": "Resistance Band", "description": "Sentadilla con banda elástica."},
    {"name": "Banded Deadlift", "type": ExerciseType.STRENGTH, "muscle_groups": ["hamstrings", "glutes", "back"], "equipment": "Resistance Band", "description": "Peso muerto con banda elástica."},
    {"name": "Banded Row", "type": ExerciseType.STRENGTH, "muscle_groups": ["back", "biceps"], "equipment": "Resistance Band", "description": "Remo con banda elástica."},
    {"name": "Banded Tricep Extension", "type": ExerciseType.STRENGTH, "muscle_groups": ["triceps"], "equipment": "Resistance Band", "description": "Extensión de tríceps con banda elástica."},
    {"name": "Banded Lateral Walk", "type": ExerciseType.STRENGTH, "muscle_groups": ["glutes", "abductors"], "equipment": "Resistance Band", "description": "Caminar lateral con mini-band en rodillas o tobillos."},
    {"name": "Banded Glute Bridge", "type": ExerciseType.STRENGTH, "muscle_groups": ["glutes", "hamstrings"], "equipment": "Resistance Band", "description": "Puente de glúteos con mini-band en rodillas."},
    {"name": "Banded Clamshell", "type": ExerciseType.STRENGTH, "muscle_groups": ["glutes", "abductors"], "equipment": "Resistance Band", "description": "Apertura de concha con mini-band de lado."},
    {"name": "Banded Face Pull", "type": ExerciseType.STRENGTH, "muscle_groups": ["rear_delts", "traps", "rotator_cuff"], "equipment": "Resistance Band", "description": "Tirón a la cara con banda elástica."},
]
